### ISSUE TITLE
Quote & Pullquote: not looking accurate in the editor and front end

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentythree#263] opened 2022-10-06 14:18 UTC
I noticed the quotes and pullquotes aren't looking the same in the editor and front end. On top of that, the pullquote needs to be polished.

**Quote:**
- Missing the vertical lines

| Frontend | Editor (Intended) |
| ---- | ---- |
| <img width="1279" alt="Captura de ecrã 2022-10-06, às 15 04 14" src="https://user-images.githubusercontent.com/65220155/194334952-3c31ab2c-8e17-4b06-a6a8-d5d2cd799f26.png"> | <img width="895" alt="Captura de ecrã 2022-10-06, às 15 04 31" src="https://user-images.githubusercontent.com/65220155/194334890-33905136-5ac9-4eb3-8135-37adcd309959.png"> |

**Pullquote:**

- Citation should be size Small
- Pullquote should be the current size with 1,3 line height
- There should be some spacing between the pull quote horizontal lines and the rest of the content

| Frontend | Editor | Intended |
| ---- | ---- | ---- |
| <img width="1111" alt="Captura de ecrã 2022-10-06, às 15 05 01" src="https://user-images.githubusercontent.com/65220155/194335150-09357f3f-4322-4d76-8d5b-3ac67761ca75.png"> | <img width="1217" alt="Captura de ecrã 2022-10-06, às 15 04 45" src="https://user-images.githubusercontent.com/65220155/194335073-7251f9cc-70c0-4caa-aa94-ffa364d81ca2.png"> | <img width="1212" alt="Captura de ecrã 2022-10-06, às 15 14 32" src="https://user-images.githubusercontent.com/65220155/194336330-46bab0c7-af00-413b-a6c4-e520cb3c642c.png"> |

**Comment by carolinan** [comment] 2022-10-06 14:22
This is a duplicate of [202](https://github.com/WordPress/twentytwentythree/issues/202)
I have made a pull request for it in Gutenberg but it still needs to be reviewed.

**Comment by beafialho** [comment] 2022-10-06 14:29
Thanks for pointing that out, I had not seen #202. But keep in mind the additional changes requested in this one.

**Closed as completed** 2022-10-10 14:27 UTC
Labels: [Type] Bug, [Type] Enhancement
