### ISSUE TITLE
Issues running into while demoing

### ISSUE THREAD

**Issue by mtias** [WordPress/twentytwentythree#164] opened 2022-09-13 14:40 UTC
- The query on the home is not inheriting query, old post link doesn't work with `?query-page=2`.
- The default set of featured images doesn't crop, so it's hard to get them aligned.

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/548849/189930963-1940f9d9-e8c5-47f4-9dbb-2c4c4e9870d0.png">

- The query on the index template does not fill the align wide width

**Comment by annezazu** [comment] 2022-09-14 01:44
Following up from today's session to add the following:  the latest PR https://github.com/WordPress/gutenberg/pull/44065 that was merged about adding justification tools that TT3 has a broken default layout. Here are screenshots from @mtias:

Editor:

<img width="1145" alt="image (21)" src="https://user-images.githubusercontent.com/26996883/190039880-b1cd5510-f018-4bed-9ef1-8a8a3e8200fc.png">

Front end works fine:

<img width="1230" alt="image (22)" src="https://user-images.githubusercontent.com/26996883/190039901-8a6421c6-0c01-47dd-b018-da595d0384cd.png">

If a GitHub issue needs to be opened in Gutenberg, happy to do so cc @tellthemachines just in case since you did the great work on the initial PR!

**Comment by andrewserong** [comment] 2022-09-14 04:53
>  TT3 has a broken default layout

@annezazu with this one, in my testing it looks like in the site editor the `alignwide` class that is set on the parent query loop block isn't being added to the child's markup (post template block) — however on the site's frontend it is. So, I'm wondering if this is a bug in either the Query Loop or Post Template block's JS where it should be inheriting the Query block's alignment class (as well as the layout settings), but it doesn't currently appear to be doing so? (Assuming the behaviour on the site frontend is the correct behaviour).

Here's a fairly large screenshot in case it helps (note the missing `alignwide` class on the `ul` element in the site editor view on the left, and its presence in the server-rendered markup on the right):

![broken-query-loop-layout](https://user-images.githubusercontent.com/14988353/190062371-292bf78f-8df5-4e81-9e83-cd816e267436.jpg)

So it looks like there might need to be an update to the Post Template or Query Loop blocks in Gutenberg to fix that up?

**Comment by tellthemachines** [comment] 2022-09-14 04:55
@annezazu I can reproduce that issue with TT3 layout in 14.0. The problem seems to be that the Post Template block has an `align: wide` attribute, but it's not getting the `alignwide` classname in the site editor. It does in the front end.

I can also see that Post Template doesn't have `wide` and `full` alignment options in the toolbar:
<img width="681" alt="Screen Shot 2022-09-14 at 2 53 26 pm" src="https://user-images.githubusercontent.com/8096000/190062705-c9fc465e-301e-4e5a-befd-d87c3498d1ca.png">
Which I'd expect it to have given it's inside a constrained layout block. That seems like a bug, I'll look into it!

**Comment by carolinan** [comment] 2022-09-14 04:58
There is an open PR that changes the layout type, perhaps that will give you a different result: #165.

**Comment by tellthemachines** [comment] 2022-09-14 05:41
[This PR](https://github.com/WordPress/gutenberg/pull/44144) should fix the issue!

**Comment by annezazu** [comment] 2022-09-14 18:43
Amazing job getting that fix in place. Thanks so much @tellthemachines!

**Closed as completed** 2022-09-19 12:04 UTC
Labels: [Type] Bug, Good First Issue
